/**
 * EOS Capture Relay MCP Server.
 *
 * This is the cross-tool bridge for Experience OS. Any MCP-capable client can
 * submit a consented collaboration fragment and read only verified experience
 * assets. It deliberately cannot create approvals or promote assets.
 */

import { stdin, stdout, stderr } from "node:process";
import { randomBytes } from "node:crypto";
import path from "node:path";
import { GitVault } from "./gitVault.js";
import { resolveVaultDir } from "./vaultPath.js";
import {
  createCapturePermitRequest,
  claimCapturePermit,
  restoreCapturePermit,
  getCapturePermitStatus
} from "./capturePermitStore.js";
import {
  captureWorkCheckpoint,
  buildProjectTimeline,
  getProjectReadiness,
  submitAgentExperienceReceiptDraft
} from "./projectEngine.js";

// GitVault may announce initialization. MCP stdout must contain JSON-RPC only.
console.log = (...args) => stderr.write(`[EOS Relay] ${args.join(" ")}\n`);

const vaultDir = resolveVaultDir("real");
const vault = new GitVault(vaultDir);
const eosDir = path.dirname(vaultDir);
const strictCapture = process.env.EOS_CAPTURE_POLICY === "strict_permit";
await vault.init();

const TOOLS = [
  {
    name: "eos_capture_collaboration",
    description: "Store one user-consented collaboration fragment as a replayable EOS work checkpoint with its source event and evidence link.",
    inputSchema: {
      type: "object",
      required: ["projectId", "actor", "content", "sourceTool", "consented"],
      properties: {
        projectId: { type: "string" },
        actor: { type: "string", description: "Usually human or the calling agent name." },
        content: { type: "string", description: "A bounded fragment the user explicitly chose to retain." },
        sourceTool: { type: "string", description: "codex, cursor, claude-code, terminal, or another source." },
        sourceRef: { type: ["string", "null"] },
        title: { type: "string", description: "Optional human-readable title for this work boundary." },
        notes: { type: "string", description: "Optional context, uncertainty, or follow-up notes." },
        permitId: { type: "string", description: "Required when this workspace enforces strict_permit capture." },
        consented: { type: "boolean", description: "Must be true; EOS rejects implicit capture." }
      }
    },
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false }
  },
  {
    name: "eos_prepare_capture_permit",
    description: "Stage one proposed collaboration fragment for human review. In strict mode this does not capture to the EOS Vault; a human must approve the request before eos_capture_collaboration can use it.",
    inputSchema: {
      type: "object",
      required: ["projectId", "actor", "content", "sourceTool"],
      properties: {
        projectId: { type: "string" }, actor: { type: "string" }, content: { type: "string" }, sourceTool: { type: "string" },
        sourceRef: { type: ["string", "null"] }, title: { type: "string" }, notes: { type: "string" }
      }
    },
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false }
  },
  {
    name: "eos_capture_permit_status",
    description: "Check whether a staged capture request is pending human approval, issued, consumed, rejected, or missing.",
    inputSchema: { type: "object", required: ["projectId", "permitId"], properties: { projectId: { type: "string" }, permitId: { type: "string" } } },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false }
  },
  {
    name: "eos_project_readiness",
    description: "Explain which Experience Receipts in a project are eligible for reusable-experience promotion and what is still missing.",
    inputSchema: {
      type: "object",
      required: ["projectId"],
      properties: { projectId: { type: "string" } }
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false }
  },
  {
    name: "eos_submit_receipt_draft",
    description: "Submit a structured Experience Receipt proposal generated by this active AI client. EOS never invokes the client's cloud model or reads credentials. The draft may cite only the supplied project's already-consented work checkpoints and always remains pending human review.",
    inputSchema: {
      type: "object",
      required: ["id", "projectId", "checkpointIds", "proposal", "agent"],
      properties: {
        id: { type: "string" },
        projectId: { type: "string" },
        checkpointIds: { type: "array", minItems: 1, items: { type: "string" } },
        proposal: {
          type: "object",
          required: ["summary"],
          properties: {
            phase: { type: "string" }, summary: { type: "string" }, outcome: { type: "string" }, uncertainty: { type: ["number", "string", "null"] },
            counterexamples: { type: ["array", "string"] }, applicabilityBounds: { type: ["array", "string"] }, lessonsLearned: { type: ["array", "string"] }
          }
        },
        agent: {
          type: "object",
          required: ["provider", "model", "actor"],
          properties: { provider: { type: "string" }, model: { type: "string" }, actor: { type: "string" }, sourceTool: { type: "string" } }
        }
      }
    },
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false }
  },
  {
    name: "eos_verified_experience",
    description: "List approved ExperienceAssets for a project, including their receipt, reviewed decision, and successful outcome references.",
    inputSchema: {
      type: "object",
      required: ["projectId"],
      properties: { projectId: { type: "string" }, limit: { type: "number", minimum: 1, maximum: 100 } }
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false }
  },
  {
    name: "eos_project_timeline",
    description: "Read the evidence-first project timeline without modifying it.",
    inputSchema: {
      type: "object",
      required: ["projectId"],
      properties: { projectId: { type: "string" } }
    },
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false }
  }
];

function textResult(value, isError = false) {
  return { content: [{ type: "text", text: JSON.stringify(value, null, 2) }], ...(isError ? { isError: true } : {}) };
}

function generatedId(prefix) {
  return `${prefix}.${Date.now()}.${randomBytes(4).toString("hex")}`;
}

async function callTool(name, args = {}) {
  if (name === "eos_prepare_capture_permit") {
    const project = await vault.load("Project", args.projectId);
    if (!project) throw new Error("project not found");
    const request = await createCapturePermitRequest(eosDir, args);
    return textResult({ ok: true, request, message: "Capture is staged locally for human review; it has not entered the EOS Vault." });
  }
  if (name === "eos_capture_permit_status") {
    const status = await getCapturePermitStatus(eosDir, args.permitId, args.projectId);
    return textResult({ projectId: args.projectId, permitId: args.permitId, status: status?.status ?? "missing", expiresAt: status?.expiresAt ?? null });
  }
  if (name === "eos_capture_collaboration") {
    let claimedPermit = null;
    if (strictCapture) {
      if (typeof args.permitId !== "string" || !args.permitId.trim()) {
        throw new Error("strict capture requires a human-issued permitId");
      }
      claimedPermit = await claimCapturePermit(eosDir, {
        id: args.permitId,
        projectId: args.projectId,
        actor: args.actor,
        content: args.content,
        sourceTool: args.sourceTool
      });
    }
    const title = typeof args.title === "string" && args.title.trim()
      ? args.title.trim()
      : String(args.content || "").trim().slice(0, 80) || "Consented collaboration checkpoint";
    try {
      const captured = await captureWorkCheckpoint(vault, {
        id: generatedId("checkpoint"),
        eventId: generatedId("event"),
        evidenceId: generatedId("evidence"),
        projectId: args.projectId,
        actor: args.actor,
        content: args.content,
        sourceTool: args.sourceTool,
        sourceRef: args.sourceRef ?? null,
        title,
        notes: typeof args.notes === "string" ? args.notes : "",
        consented: args.consented,
        capturePermitId: claimedPermit?.id ?? null
      });
      return textResult({ ok: true, ...captured, permitId: claimedPermit?.id ?? null, message: "Captured locally with explicit consent as a work checkpoint." });
    } catch (error) {
      if (claimedPermit) await restoreCapturePermit(eosDir, claimedPermit.id);
      throw error;
    }
  }
  if (name === "eos_project_readiness") {
    return textResult(await getProjectReadiness(vault, args.projectId));
  }
  if (name === "eos_submit_receipt_draft") {
    const draft = await submitAgentExperienceReceiptDraft(vault, args);
    return textResult({ ok: true, draft, message: "Agent-hosted draft saved locally. It remains pending human review and is not an ExperienceReceipt or verified asset." });
  }
  if (name === "eos_verified_experience") {
    const limit = Math.min(Math.max(Number(args.limit) || 20, 1), 100);
    const assets = (await vault.list("ExperienceAsset"))
      .filter((asset) => asset.projectId === args.projectId && asset.status === "approved")
      .sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))
      .slice(0, limit);
    return textResult({ projectId: args.projectId, count: assets.length, assets });
  }
  if (name === "eos_project_timeline") {
    return textResult(await buildProjectTimeline(vault, args.projectId));
  }
  throw new Error(`Unknown tool: ${name}`);
}

async function handleMessage(message) {
  if (message.method === "initialize") {
    return {
      jsonrpc: "2.0",
      id: message.id,
      result: {
        protocolVersion: "2024-11-05",
        capabilities: { tools: {} },
        serverInfo: { name: "experience-os-capture-relay", version: "3.0.0" }
      }
    };
  }
  if (message.method === "notifications/initialized") return null;
  if (message.method === "tools/list") return { jsonrpc: "2.0", id: message.id, result: { tools: TOOLS } };
  if (message.method === "tools/call") {
    try {
      return { jsonrpc: "2.0", id: message.id, result: await callTool(message.params?.name, message.params?.arguments) };
    } catch (error) {
      return { jsonrpc: "2.0", id: message.id, result: textResult({ error: error.message }, true) };
    }
  }
  return { jsonrpc: "2.0", id: message.id, error: { code: -32601, message: `Method not found: ${message.method}` } };
}

let buffer = "";
let processingQueue = Promise.resolve();
stdin.setEncoding("utf8");
stdin.on("data", (chunk) => {
  buffer += chunk;
  let newline;
  while ((newline = buffer.indexOf("\n")) >= 0) {
    const line = buffer.slice(0, newline).trim();
    buffer = buffer.slice(newline + 1);
    if (!line) continue;
    // Serialize message processing to prevent concurrent writes and race conditions
    processingQueue = processingQueue.then(async () => {
      try {
        const reply = await handleMessage(JSON.parse(line));
        if (reply) stdout.write(`${JSON.stringify(reply)}\n`);
      } catch (error) {
        // Try to extract the original request id for error correlation
        let requestId = null;
        try { requestId = JSON.parse(line).id ?? null; } catch { /* not valid JSON */ }
        stdout.write(`${JSON.stringify({ jsonrpc: "2.0", id: requestId, error: { code: -32700, message: error.message } })}\n`);
      }
    }).catch((err) => {
      stderr.write(`[EOS Relay] message processing error: ${err.message}\n`);
    });
  }
});

// Exit cleanly when stdin closes (MCP client disconnected)
stdin.on("end", () => process.exit(0));
stdin.on("close", () => process.exit(0));
